---
- name: Windows Updatesによりアップデートすべき内容の一覧取得
  hosts: all

  tasks:

  - name: Windows Updatesによるアップデート検索結果の取得
    win_updates:
      state: searched
      category_names: 
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
    register: update_results

  - name: リストの表示
    debug:
      msg: "{{ update_results.updates }}"
